version: "3.8"

volumes:
  data:

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Fampay
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user1234


  redis:
    image: redis:latest  
  api:
    build:
      context: ./FetchApi  
    restart: always
    command: >
      /bin/bash -c "
        python3 manage.py makemigrations &&  
        python3 manage.py migrate && 
        python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./FetchApi/:/usr/src/code/
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  celery:
    build:
      context: ./FetchApi
    restart: always
    command: celery -A FetchApi worker -l INFO
    volumes:
      - ./FetchApi/:/usr/src/code/
    depends_on:
      - db
      - redis
      - api
  celery-beat:
    build:
      context: ./FetchApi
    restart: always
    command: celery -A FetchApi beat -l INFO
    volumes:
      - ./FetchApi/:/usr/src/code/
    depends_on:
      - db
      - redis
      - api






   
     