version: "3.8"

volumes:
  data:

services:

  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE='Fampay'
      - MYSQL_ROOT_PASSWORD='admin@123'    
    volumes:
      - ./data:/var/lib/mysql

  redis:
    image: redis:latest  
  api:
    build:
      context: ./FetchApi  
    restart: always
    command: >
      /bin/bash -c "
        python3 manage.py makemigrations && 
        python3 manage.py migrate && 
        python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./FetchApi/:/usr/src/code/
    ports:
      - 8000:8000
    links:
      - mysqldb
    depends_on:
      - redis
      - mysqldb

  celery:
    build:
      context: ./FetchApi
    restart: always
    command: celery -A FetchApi worker -l INFO
    volumes:
      - ./FetchApi/:/usr/src/code/
    depends_on:
      - mysqldb
      - redis
  






   
     