version: "3.8"

volumes:
  data:

services:
  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file:
      - ./.env     
    volumes:
      - ./data:/var/lib/mysql

  api:
    build:
      context: ./FetchApi  
    restart: always
    command: >
      /bin/bash -c "
        python3 ./FetchApi/manage.py makemigrations && 
        python3 ./FetchApi/manage.py migrate && 
        python3 ./FetchApi/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - mysqldb
    depends_on:
      - mysqldb






   
     