# Generated by Django 4.0.6 on 2022-07-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YTVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.CharField(max_length=200)),
                ('channel_id', models.CharField(max_length=100)),
            ],
        ),
    ]
