# Generated by Django 4.0.6 on 2022-07-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIkey',
        ),
    ]
