FROM python:3

# Set environment variables
ENV PYTHONUNBUFFERED 1

WORKDIR /code

ADD . /code

COPY ./requirements.txt  /code/requirements.txt

# Install dependencies.
RUN pip3 install -r /code/requirements.txt



