FROM python:3

# Set environment variables
ENV PYTHONUNBUFFERED 1

WORKDIR /code

ADD . /code

COPY ./requirements.txt  /code/requirements.txt

# Install dependencies.
RUN pip install -r /code/requirements.txt

# Copy project code.
# COPY . /code

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000"]