FROM python:3

# Set environment variables
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/code/

ADD . /usr/src/code/

COPY ./requirements.txt  /usr/src/code/requirements.txt

# Install dependencies.
RUN pip3 install -r /usr/src/code/requirements.txt



